name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  flutter_dotenv: ^5.0.2

  english_words: ^4.0.0
  provider: ^6.1.2
  #cloud_firestore: ^4.8.0
  #firebase_core: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      # - .env