// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvlvv5h_XkA6ZOEW6kWiPN3CHAdd_ZsEE',
    appId: '1:1096761458761:web:4592fb059e5eef81643f98',
    messagingSenderId: '1096761458761',
    projectId: 'ai-tutor-b26e6',
    authDomain: 'ai-tutor-b26e6.firebaseapp.com',
    databaseURL: 'https://ai-tutor-b26e6-default-rtdb.firebaseio.com',
    storageBucket: 'ai-tutor-b26e6.firebasestorage.app',
    measurementId: 'G-2KEGNPG41S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrcYPE3plmeqmi2TrQ2poqrcd63rEIGag',
    appId: '1:1096761458761:android:02ea0bc802cbd95b643f98',
    messagingSenderId: '1096761458761',
    projectId: 'ai-tutor-b26e6',
    databaseURL: 'https://ai-tutor-b26e6-default-rtdb.firebaseio.com',
    storageBucket: 'ai-tutor-b26e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJHy6zKlJVIsQ0ufiRY-EbzdA_JlZtFDA',
    appId: '1:1096761458761:ios:7228c9d3f7cf26f6643f98',
    messagingSenderId: '1096761458761',
    projectId: 'ai-tutor-b26e6',
    databaseURL: 'https://ai-tutor-b26e6-default-rtdb.firebaseio.com',
    storageBucket: 'ai-tutor-b26e6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJHy6zKlJVIsQ0ufiRY-EbzdA_JlZtFDA',
    appId: '1:1096761458761:ios:7228c9d3f7cf26f6643f98',
    messagingSenderId: '1096761458761',
    projectId: 'ai-tutor-b26e6',
    databaseURL: 'https://ai-tutor-b26e6-default-rtdb.firebaseio.com',
    storageBucket: 'ai-tutor-b26e6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvlvv5h_XkA6ZOEW6kWiPN3CHAdd_ZsEE',
    appId: '1:1096761458761:web:c679cb5571a1f6eb643f98',
    messagingSenderId: '1096761458761',
    projectId: 'ai-tutor-b26e6',
    authDomain: 'ai-tutor-b26e6.firebaseapp.com',
    databaseURL: 'https://ai-tutor-b26e6-default-rtdb.firebaseio.com',
    storageBucket: 'ai-tutor-b26e6.firebasestorage.app',
    measurementId: 'G-107XXSN6PL',
  );
}
